services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    command: sh -c "npm install && npm i sharp && npx next telemetry disable && npm run build && npm start"